AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  scrapers

  Sample SAM Template for scrapers

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  ScrapersNeweggFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: sites/newegg
      Handler: app.lambda_handler
      Runtime: python3.8

  ScrapersBestBuyCaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: sites/bestbuyca
      Handler: app.lambda_handler
      Runtime: python3.8
#      Events:
#        HelloWorld:
#          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
#          Properties:
#            Path: /hello
#            Method: get

#Outputs:
#  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
#  # Find out more about other implicit resources you can reference within SAM
#  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
#  ScrapersSitesApi:
#    Description: "API Gateway endpoint URL for Prod stage for Scrapers Sites function"
#    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
#  ScrapersSitesFunction:
#    Description: "Scrapers Sites Function ARN"
#    Value: !GetAtt ScrapersAllSitesFunction.Arn
#  ScrapersSitesFunctionIamRole:
#    Description: "Implicit IAM Role created for Scrapers Sites Function"
#    Value: !GetAtt ScrapersAllSitesFunction.Arn
